### ISSUE TITLE
Hitting enter when submitting "track" data submits form

### ISSUE THREAD

**Issue by MoodlyTracker** [lzinga/moodly-issues#15]
When entering tags, it's expected to hit "enter" in order to finalize the current tag, but doing so instead submits the whole mood form.

I think it'd be nice to remove this.

---
⚠ *Do not edit this section. GitHub issue linking.* ⚠
* ID: c81e728d9d4c2f636f067f89cc14862c

**Comment by Janooba** [comment]
This happens on mobile too, when hitting the enter/new line button on the keyboard.
