### ISSUE TITLE
Filtering by date removes data from view

### ISSUE THREAD

**Issue by MoodlyTracker** [lzinga/moodly-issues#9]
Clicking the checkmark to filter by date seems to show blank results.

https://puu.sh/DkVgK/bef1d86f25.png

---
⚠ *Do not edit this section. GitHub issue linking.* ⚠
* ID: c81e728d9d4c2f636f067f89cc14862c

**Comment by lzinga** [comment]
Doing a quick test it looks like every time you click it, it subtracts one day from each side.

**Comment by lzinga** [comment]
This has been fixed and deployed to the latest version.
